== Capítulo 3: Patrones y secuencias

En este capítulo hablaremos sobre los patrones y secuencias, cuáles son las principales diferencias y cómo podemos crear reglas acorde a ellos.

=== Patrones

Los patrones permiten a los flujos de eventos correlar en el tiempo y detectar patrones basados en un orden de llegada. Con los patrones puede haber otros eventos entre aquellos que hacen _match_ con nuestra regla. Los patrones pueden correlar los eventos de múltiples fuentes o de una única fuente, por lo tanto cada evento que haga _match_ necesita ser referenciado para que pueda ser accedido en el futuro para su procesado y generación de su salida.

La sintaxis de un patrón es como sigue a continuación:

*****
*from* {*every*} <input event reference>=<input stream name>[<filter condition>] -&#62; {*every*} <input event reference>=<input stream name>[<filter condition>] -&#62; ...
    *within* <time gap>
*select* <input event reference>.<attribute name>, <input event reference>.<attribute name>, ...
*insert into* <output stream name>
*****

En esta sintaxis podemos apreciar varios detalles:

* En la expresión `{every} <input event reference>=<input stream name>[<filter condition>] -&#62;`:
** La palabra clave `*every*` indica si queremos que el patrón sólo haga _match_ una única vez (omitiendo dicha palabra clave). Hay que usar apropiadamente esta palabra reservada, ya que si la utilizamos, el patrón hará _match_ por cada evento que cumpla la condición.
** `<input event reference>=` es la referencia del evento que ha hecho _match_ para su posible uso en el futuro.
** `<input stream name>[<filter condition>]` es el flujo de eventos de entradas. Pueden aplicarse filtros para excluir aquellos eventos que no cumplan con las condiciones que se especifiquen.
** `-&#62;` con este operador podemos correlar la llegada de los eventos entrantes, pudiendo tener varios eventos entre aquellos que hacen _match_.

WARNING: Hay que tener en cuenta que a los flujos de entradas no se le pueden asociar ventanas de tiempo.

Para establecer un intervalo de tiempo en el que evaluar el patrón se utiliza la expresión `within <time gap>`. `<time gap>` es una expresión que utiliza el tipo especial de datos `Time`. `Time` es un tipo compuesto por un entero (`int`) y una unidad (`unit`) de tiempo, el tipo de datos `Time` realmente devuelve un número de tipo `long`, así que simplemente es un tipo que ayuda al usuario a definir intervalos de tiempo de una forma más cómoda y natural. En la siguiente tabla podemos observar los tipos de unidades así como ejemplos:

[grid="rows",format="csv"]
[options="header",cols="^,^,^,^"]
|======================
Unidad, Sintaxis, Ejemplo, Devuelve
Año, year | years, 1 year, 217728000000
Mes, month | months, 1 month, 18144000000
Semana, week | weeks, 1 week, 604800000
Day, day | days, 1 day, 86400000
Hour, hour | hours, 1 hour, 3600000
Minutos, minute | minutes | min, 1 min, 60000
Segundos, second | seconds | sec, 1 sec, 1000
Milisegundos, millisecond | milliseconds, 1 millisecond, 1
|======================

El tipo `Time` no está limitado a sólo el uso de un tipo de unidad, sino que puede combinarse con varias unidades para hacer intervalos más precisos, como por ejemplo: `1 hour 30 min` para indicar una hora y media devolviendo como resultado `5400000`.

Hay que tener en cuenta que cuando se utiliza la expresión `within <time gap>` estamos estableciendo un intervalo en el cual todos los patrones tienen que hacer _match_. En caso contrario todos los eventos que han hecho _match_ y a los cuales se tienen referencia serán descartados, comenzando de nuevo con el proceso.

Para asentar mejor lo explicado, vamos a analizar el siguiente patrón de ejemplo:

*****
*from every* (e1=TempStream) -&#62; e2=TempStream[e1.roomNo==roomNo *and* (e1.temp + 5) <&#61; temp]
    *within* 10 min
*select* e1.roomNo, e1.temp *as* initialTemp, e2.temp *as* finalTemp
*insert into* AlertStream;
*****

En primer lugar tenemos la expresión `every e1=TempStream`, con la que simplemente estamos capturando los eventos del flujo `TempStream` y los estamos referenciando con `e1`. Podemos observar que tenemos la palabra clave `every` indicando de esta forma que este patrón puede hacer _match_ en más de una ocasión. Como no hay filtros aplicados este patrón hará _match_ por cada evento que llegue de entrada y estos serán almacenados con sus correspondientes referencias.

En segundo lugar tenemos la expresión `e2=TempStream[e1.roomNo==roonNo and (e1.temp + 5) <&#61; temp ]` en este caso estamos capturando un evento que cumpla con el siguiente filtro:

* Si el número de habitación del último evento recibido del primer patrón (`e1`) coincide con el número de habitación del segundo evento (Para hacer uso de los atributos de los eventos capturados no se utiliza ningún tipo de referencia)
* Y si la temperatura ha incrementado en 5 grados con respecto al último evento recibido del primer patrón pero es menor o igual que el del propio evento capturado.

Entonces el patrón completo hace _match_, obteniendo el número de habitación, la temperatura inicial y la temperatura final inyectando los datos en el flujo de salida `AlertStream`. Sin embargo debemos de tener en cuenta la expresión `within 10 min` que nos indica que todas estas condiciones tienen que cumplirse en un intervalo de tiempo de 10 minutos.

Por lo tanto esta regla se leería de la siguiente forma: *_Alerta cuando la temperatura de una habitación incremente 5 grados en un intervalo de 10 minutos_*

A continuación veremos dos tipos de patrones que pueden utilizarse para dar más flexibilidad a este tipo de correlación.

==== Patrones lógicos

Los patrones no tienen por qué hacer _match_ cuando llegan los eventos en un orden temporal, en ocasiones necesitaremos relaciones lógicas para definir el comportamiento de un patrón y así ofrecer más flexibilidad.

Las palabra claves como `and` (conjunción lógica "Y") y `or` (disyunción lógica "O") pueden ser utilizadas en lugar de "-&#62;" para ilustrar relaciones lógicas.

* Con el operador `and` deben de cumplirse las condiciones de dos eventos para que el patrón pueda hacer _match_.
* Con el operador `or` debe de cumplirse al menos una de las condiciones para que el patrón pueda hacer _match_.

Veamos el siguiente ejemplo:

*****
*from every* (e1=RegulatorStream) -&#62; e2=TempStream[e1.roomNo==roomNo *and* e1.tempSet <&#61; temp] *or* e3=RegulatorStream[e1.roomNo==roomNo]
*select* e1.roomNo, e2.temp *as* roomTemp
*having* e3 *is* null
*insert into* AlertStream;
*****

Este ejemplo se parece mucho al visto en la sección anterior, sin embargo podemos ver la siguiente expresión: `e2=TempStream[e1.roomNo==roomNo and e1.tempSet <&#61; *temp* ] or e3=RegulatorStream[e1.roomNo==roomNo]`

En dicha expresión estamos evaluando que si la habitación es la mismas para el evento del primer patrón y la temperatura es menor o igual que el evento del segundo patrón o si por el contrario no lo es pero en cambio sí coincide que la habitación es la misma para el evento del tercer patrón. Entonces hace _match_ y se dispara.

Sin embargo debemos de tener en cuenta la expresión `having e3 is null`. La palabra reservada `having` nos permite filtrar los eventos después de una agregación o de un procesado de eventos. Así finalmente estamos añadiendo un filtro en el cual estamos especificando que el evento del tercer patrón (referenciado como `e3`) tiene que ser nulo, condición que se cumple si el primer patrón y el segundo patrón se cumplen. En caso contrario no se disparará el patrón.

==== Patrones de conteo

Los patrones de conteo nos permiten hacer _match_ de múltiples eventos que contemplan la misma condición. El número de eventos esperados puede ser limitado usando los siguientes operadores:

* Con `<N:M>` contará de `N` a `M` eventos, así por ejemplo `<1:4>` contará de 1 a 4 eventos.
* Con `<N:>` contará a partir de `N` eventos, así por ejemplo `<2:>` contará a partir de 2 eventos.
* Con `<:M>` contará hasta `M` eventos, así por ejemplo `<:5>` contará hasta 5 eventos.
* Con `<X>` contará exactamente `X` eventos, así por ejemplo `<5>` contará exactamente 5 eventos.

WARNING: La diferencia entre `<:M>` y `<X>` es que con el operador `<X>` estamos indicando que el patrón se tiene que cumplir exactamente X veces para que ocurra un _match_ mientras que con el operador `<:M>` estamos indicando que se puede cumplir hasta M veces pero haciendo _match_ por cada vez.

Observemos la siguiente regla:

*****
*from every* (e1=RegulatorStream) -&#62; e2=TempStream[e1.roomNo==roomNo]<1:> -&#62; e3=RegulatorStream[e1.roomNo==roomNo]
*select* e1.roomNo, e2[0].temp - e2[*last*].temp *as* tempDiff
*insert into* TempDiffStream;
*****

En ella tenemos la siguiente expresión `e2=TempStream[e1.roomNo==roomNo]<1:>` de conteo definido, para este caso estamos poniendo como limitante que haya uno o más eventos para poder hacer _match_.

=== Secuencias

Las secuencias, al igual que los patrones, permiten correlar sobre los eventos recibidos y detectar secuencias de eventos según su orden de llegada. A diferencia de los patrones, en una secuencia no puede haber otros eventos entre aquellos que hacen _match_ con nuestra regla. Las secuencias pueden currerlar los eventos de múltiples fuentes o de una única fuente, por lo tanto cada evento que haga _match_ necesita ser referenciado para que pueda ser accedido en el futuro para su procesado y generación de su salida.

La sintaxis de una secuencia es como sigue a continuación:

****
*from* {*every*} <input event reference>=<input stream name>[<filter condition>], <input event reference>=<input stream name>[<filter condition>]{+|&#42;|?}, ...
    *within* <time gap>
*select* <input event reference>.<attribute name>, <input event reference>.<attribute name>, ...
*insert into* <output stream name>
****

Al igual que ocurre con los patrones, las secuencias no pueden tener una ventana asociada. Podemos observar que hay una gran similitud en cuanto a los patrones con la única diferencia en que el delimitador es una coma (`,`). El resto de elementos son totalmente análogos al uso de patrones salvo el conteo que se explicará en sucesivas secciones.

==== Secuencias lógicas

Las secuencias no sólo hacen _match_ en eventos consecutivos sino que pueden ser correlados con relaciones lógicas. Para ello podemos utilizar las palabras claves `and` y `or` del mismo modo que se utilizand en los patrones.

Por ejemplo

*****
*from every* e1=RegulatorStream, e2=TempStream *and* e3=HumidStream
*select* e2.temp, e3.humid
*insert into* StateNotificationStream;
*****

En el ejemplo anterior estamos indicando que cuando llegue un evento del flujo de eventos del regulador y seguidamente llegue un evento del sensor de temperatura y de humedad, obtengamos la temperatura y humedad de cada evento y lo notifiquemos.

WARNING: Tengamos en cuenta nuevamente que es necesario que los eventos sean consecutivos no pudiendo existir otros eventos que no sean relevantes entre cada _match_ de la regla.


==== Secuencias de conteo

Las secuencias nos permite hacer _match_ con múltiples eventos consecutivos en base a unas condiciones. A diferencia de los patrones, las secuencias tiene otros limitadores de eventos que se resumen a continuación:

* Con `*` estamos indicando ninguno o muchos.
* Con `+` estamos indicando uno o muchos.
* Con `?` estamos indicando ninguno o uno.

Tal y como ocurre con los patrones, se puede hacer referencia a los eventos capturados utilizado los índices o la palabra clave `last`.

*****
*from every* e1=TempStream, e2=TempStream[e1.temp <&#61; temp]+, e3=TempStream[e2[*last*].temp > temp]
*select* e1.temp *as* initialTemp, e2[*last*].temp *as* peakTemp
*insert into* TempDiffStream;
*****

En el ejemplo anterior podemos ver la expresión `e2=TempStream[e1.temp <&#61; temp]+` donde estamos indicando que se reciban uno o más eventos.



